"""modify userModel

Revision ID: 1662c30b00ba
Revises: cc9989a75ed1
Create Date: 2019-05-05 19:26:57.356811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1662c30b00ba'
down_revision = 'cc9989a75ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
