"""modify userModel

Revision ID: 27a34bb734f1
Revises: 1662c30b00ba
Create Date: 2019-05-05 21:15:09.149205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27a34bb734f1'
down_revision = '1662c30b00ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num', table_name='tb_users')
    op.drop_column('tb_users', 'phone')
    op.drop_column('tb_users', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('num', mysql.VARCHAR(length=11), nullable=True))
    op.add_column('tb_users', sa.Column('phone', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('num', 'tb_users', ['num'], unique=True)
    # ### end Alembic commands ###
