"""update products

Revision ID: 2ec42edc50cd
Revises: 27a34bb734f1
Create Date: 2019-08-19 13:34:31.916057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec42edc50cd'
down_revision = '27a34bb734f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
