"""update permission group

Revision ID: 366258d6b888
Revises: 5c9696389389
Create Date: 2019-04-07 10:04:11.494070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366258d6b888'
down_revision = '5c9696389389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permission_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tb_permission', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_permission', 'tb_permission_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_permission', type_='foreignkey')
    op.drop_column('tb_permission', 'group_id')
    op.drop_table('tb_permission_group')
    # ### end Alembic commands ###
