"""initdb

Revision ID: 4ad4e7e01a9e
Revises: 
Create Date: 2019-03-11 21:56:45.872791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad4e7e01a9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_num', sa.Integer(), nullable=True),
    sa.Column('_locked', sa.Boolean(), nullable=False),
    sa.Column('_avatar', sa.String(length=128), nullable=True),
    sa.Column('_is_delete', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('num', sa.String(length=11), nullable=True),
    sa.Column('qq', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users')
    # ### end Alembic commands ###
