"""update decimal to 10,2

Revision ID: 59f53f8f5831
Revises: 9984f4332ee9
Create Date: 2019-08-19 15:00:10.420672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f53f8f5831'
down_revision = '9984f4332ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
