"""del code permissionModel

Revision ID: 5ae6b4681e12
Revises: f3fde1936ff2
Create Date: 2019-04-28 17:13:44.949639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ae6b4681e12'
down_revision = 'f3fde1936ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_permission', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_permission', sa.Column('code', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
