"""permission add description

Revision ID: 769daf4c81d6
Revises: 5ae6b4681e12
Create Date: 2019-05-02 23:11:34.130760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769daf4c81d6'
down_revision = '5ae6b4681e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_permission', sa.Column('description', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_permission', 'description')
    # ### end Alembic commands ###
