"""initdb

Revision ID: 7ce419625e9a
Revises: 
Create Date: 2019-03-24 10:41:08.604632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce419625e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('num', sa.String(length=11), nullable=True),
    sa.Column('qq', sa.String(length=13), nullable=True),
    sa.Column('_locked', sa.Boolean(), nullable=False),
    sa.Column('_is_delete', sa.Boolean(), nullable=False),
    sa.Column('_avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tb_foreign_oauth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('oauth_name', sa.String(length=32), nullable=True),
    sa.Column('oauth_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_expires', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_local_oauth',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_local_oauth')
    op.drop_table('tb_foreign_oauth')
    op.drop_table('tb_users')
    op.drop_table('tb_product')
    # ### end Alembic commands ###
