"""change modules name

Revision ID: 9984f4332ee9
Revises: d6c7aa01fdd0
Create Date: 2019-08-19 14:53:50.743091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9984f4332ee9'
down_revision = 'd6c7aa01fdd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_product_sku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True, comment='产品关联键'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='SKU名称'),
    sa.Column('description', sa.String(length=128), nullable=True, comment='SKU描述'),
    sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='SKU价格'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='SKU库存'),
    sa.CheckConstraint('stock >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_product_sku')
    # ### end Alembic commands ###
