"""添加关系表

Revision ID: a9127f6787b6
Revises: e58485ffee52
Create Date: 2019-03-30 17:41:16.110233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9127f6787b6'
down_revision = 'e58485ffee52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
