"""测试alembic

Revision ID: b1ccc586aa76
Revises: 59f53f8f5831
Create Date: 2020-01-09 22:06:47.169576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ccc586aa76'
down_revision = '59f53f8f5831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('num', sa.String(length=11), nullable=True))
    op.add_column('tb_users', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'tb_users', ['num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_users', type_='unique')
    op.drop_column('tb_users', 'phone')
    op.drop_column('tb_users', 'num')
    # ### end Alembic commands ###
