"""update group table

Revision ID: b68ffb464d9a
Revises: 09256f0a9372
Create Date: 2019-04-07 11:01:54.310559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68ffb464d9a'
down_revision = '09256f0a9372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
