"""撤回修改

Revision ID: ba4be5635718
Revises: b1ccc586aa76
Create Date: 2020-01-09 22:09:29.834525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4be5635718'
down_revision = 'b1ccc586aa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num', table_name='tb_users')
    op.drop_column('tb_users', 'num')
    op.drop_column('tb_users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('phone', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('tb_users', sa.Column('num', mysql.VARCHAR(length=11), nullable=True))
    op.create_index('num', 'tb_users', ['num'], unique=True)
    # ### end Alembic commands ###
