"""modify userModel

Revision ID: cc9989a75ed1
Revises: 769daf4c81d6
Create Date: 2019-05-05 19:25:59.414311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc9989a75ed1'
down_revision = '769daf4c81d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('is_admin', sa.Integer(), nullable=True))
    op.drop_column('tb_users', 'gid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('gid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('tb_users', 'is_admin')
    # ### end Alembic commands ###
