"""添加关系表

Revision ID: e58485ffee52
Revises: a8ca36c1995d
Create Date: 2019-03-30 16:46:22.891218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58485ffee52'
down_revision = 'a8ca36c1995d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permission_handler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['tb_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permission_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['tb_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_permission_role',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tb_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('permission_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_permission_role')
    op.drop_table('tb_permission_menu')
    op.drop_table('tb_permission_handler')
    op.drop_table('tb_permission')
    # ### end Alembic commands ###
