"""handler prm

Revision ID: f3fde1936ff2
Revises: b68ffb464d9a
Create Date: 2019-04-28 17:11:32.892182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fde1936ff2'
down_revision = 'b68ffb464d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_permission', sa.Column('handler', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_permission', 'handler')
    # ### end Alembic commands ###
